runtime: nodejs20
instance_class: F1

env_variables:
NODE_ENV: "production"
MONGO_URI: "mongodb+srv://admin:admin@poppinsapp.yn9j9yi.mongodb.net/?retryWrites=true&w=majority&appName=poppinsApp"
JWT_SECRET: "Nomegust@l@r3mol@ch@"